name: 💥 Wakatime Update Stats

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create folder
        run: mkdir -p wakatime

# Barras verticais
      - name: All Languages Bar
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          curl -fsSL "https://wakatime-readme-stats.vercel.app/api/wakatimeStats?username=$GITHUB_ACTOR&api_key=$WAKATIME_API_KEY&component1_type=all_langs&component1_chart_type=bar_vertical&component1_num_langs=12&component1_scale_value=2.2&theme=dark&bg_color=0d1117&title_color=58a6ff&text_color=8b949e&logo_color=58a6ff&border_color=30363d&border_radius=16" \
            -o wakatime/all_projs_bar_vertical.svg

      # Spedometer
      - name: Spedometer
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          curl -fsSL "https://wakatime-readme-stats.vercel.app/api/wakatimeStats?username=$GITHUB_ACTOR&api_key=$WAKATIME_API_KEY&component1_type=spedometer&theme=dark&bg_color=0d1117&title_color=58a6ff&text_color=8b949e&logo_color=58a6ff&border_color=30363d&border_radius=16" \
            -o wakatime/spedometer.svg

      # Rank
      - name: Rank
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          curl -fsSL "https://wakatime-readme-stats.vercel.app/api/wakatimeStats?username=$GITHUB_ACTOR&api_key=$WAKATIME_API_KEY&github_token=$GITHUB_TOKEN&component1_type=rank&component1_default_source=waka&component1_mode=level&component1_show_icons=true&theme=dark&bg_color=0d1117&title_color=58a6ff&text_color=8b949e&logo_color=58a6ff&border_color=30363d&border_radius=0&border_width=0" \
            -o wakatime/weekly_ranking.svg

      # Heatmap
      - name: Heatmap
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          curl -fsSL "https://wakatime-readme-stats.vercel.app/api/wakatimeStats?username=$GITHUB_ACTOR&api_key=$WAKATIME_API_KEY&component1_type=heatmap&theme=dark&bg_color=0d1117&title_color=58a6ff&text_color=8b949e&logo_color=58a6ff&border_color=30363d&border_radius=16" \
            -o wakatime/heatmap.svg

      - name: Cache Buster
        run: |
          V="$(date -u +%Y%m%d%H%M)"
          sed -i -E "s#(wakatime/.*\.svg)\?v=[0-9]+#\1?v=$V#g" README.md
          sed -i -E "s#(wakatime/.*\.svg)(\"|')#\1?v=$V\2#g" README.md

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add wakatime/*.svg README.md
          git diff --cached --quiet && echo "No changes" && exit 0
          git commit -m "WakaTime cards - versão estável"
          git push
